### ISSUE TITLE
how to launch this pixel3d tool after cmake building

### ISSUE THREAD

**Issue by Mrcaoyu1** [Nor-s/Pixel3D#1]
hi, I generated "mediapipe to mixamo" repo's result.json，and how can I put result.json on the mixamo model? I found this pixel3d tool, but i can't launch this tool and perform the window in your readme when i finished cmake building. could you please give me some advice, thx

**Comment by Nor-s** [comment]
@Mrcaoyu1  Sorry for not being able to help. 
You can use the mediapipe to mixamo feature simply by using the [Anim](https://github.com/Nor-s/Anim/releases/tag/v0.1.0-fix-a) project's executable file.
Anim projects do not have pixel features instead.
