### ISSUE TITLE
animation was not fully correct

### ISSUE THREAD

**Issue by jinfagang** [Nor-s/Pixel3D#5]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/21303438/172047128-e7a1d150-3219-4e79-951b-e51e6445964a.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/21303438/172047138-dead3f99-0d86-49fb-bcd5-b8c06d2d89a3.png">

the bones seems opposite, all fbx are same behavior.

and this was:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/21303438/172047191-7c90da1c-392b-45d1-a63b-7fcce08002d7.png">

default zombies also seems oppsited:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/21303438/172047223-66ef9a49-75c8-4cc2-b934-79d9493c9576.png">

**Comment by jinfagang** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/21303438/172047246-98e32980-16b0-49d5-ad04-8f1255e5f1a6.png">

**Comment by Nor-s** [comment]
Wow...it's really hard to deal with model files. 

If you built it yourself

What compiler did you use?

And I forgot to update the README.md.
Did you ever use --recursive when cloning?

Here's what I just built from the main branch.... with gcc10.3.0 x86_64-w64-mingw32 (windows11)

![image](https://user-images.githubusercontent.com/40836757/172048571-72880721-f457-412d-8f15-ac05e8d258a2.png)

I will build and test it in various environments. Thanks for the issue!

**Comment by jinfagang** [comment]
@Nor-s I am on macOS with clang 11.3.

which assimp version did u using? I using assimp updated to this commit: abfb26ab6f2b350d604ad1e653250c998579c41f

the only differences between you and me should be assimp, since I am not using your submodule commit id, I can not pull it due to poor network speed in China behind GFW, so I just cloned it with master branch.

Can u try update to master assimp master branch? it should have some bias between our two sides.

**Comment by Nor-s** [comment]
This also seems to be a flag issue!

I tested it with the assimp on Mac OS with clang12 and it was normal.

 However

I was able to reproduce the error by setting the assimp's flags as follows:

```cpp
        AssimpAnimation(const char *animation_path)
        {
            type = AnimationType::Assimp;
            Assimp::Importer importer;
            unsigned int assimp_read_flag =
                aiProcess_SortByPType |
                aiProcess_ConvertToLeftHanded |
                aiProcess_ValidateDataStructure |
                aiProcess_LimitBoneWeights;
```
<img width="585" alt="스크린샷 2022-06-06 오전 12 04 23" src="https://user-images.githubusercontent.com/40836757/172057073-1d1d2bcc-2367-42b0-a76a-687e2405fc1d.png">
<img width="585" alt="스크린샷 2022-06-06 오전 12 04 12" src="https://user-images.githubusercontent.com/40836757/172057087-67c34c3b-86f2-46fb-bc9c-e9318ccb0fe4.png">

`                aiProcess_ConvertToLeftHanded | `
I don't know why, but if you use that flag in your code, it might work.

**Comment by jinfagang** [comment]
@Nor-s I didn't change the code, should be same as yours. let me have a try, if your code same as mine, I maybe should using `aiProcess_ConvertToRightHanded` to inverse it again, which is really strange.

**Comment by jinfagang** [comment]
@Nor-s  Hi, I am uncomment that flag (it was just comment out when clone), not it looks lack some mesh:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/21303438/172176294-78e6c9d2-0b43-4cce-b5eb-e75d48063317.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/21303438/172176336-7435543b-cd1b-42f7-ad36-56440a8a8118.png">


the flags:

```
 Assimp::Importer import;
        unsigned int assimp_read_flag = aiProcess_Triangulate |
                                        aiProcess_SortByPType |
                                        aiProcess_GenUVCoords |
                                        aiProcess_OptimizeMeshes |
                                        aiProcess_ValidateDataStructure |
                                        aiProcess_ConvertToLeftHanded |
                                        // aiProcess_FlipUVs |
                                        aiProcess_GenNormals |
                                        aiProcess_CalcTangentSpace;
        assimp_read_flag |= aiProcess_LimitBoneWeights;
        assimp_read_flag |= aiProcess_JoinIdenticalVertices;
        assimp_read_flag |= aiProcess_FlipWindingOrder;
        import.SetPropertyBool(AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, false);
```

**Comment by Nor-s** [comment]
You need to modify [the AssimpAnimation class. ](https://github.com/Nor-s/Pixel3D/blob/21b72733f0a24a51e070a438522827acb3d9b10f/src/glcpp/anim/assimp_animation.hpp#L28)

not model.cpp

**Comment by jinfagang** [comment]
@Nor-s thanks for the info, will try it later. But I have a question, doesn't fbx animation baked in? Why there should another reading process for the animation?

**Comment by Nor-s** [comment]
@jinfagang

There was no other reason. 
[The reference](https://learnopengl.com/Guest-Articles/2020/Skeletal-Animation) I saw when I was learning the skeleton was just such a structure.

In my opinion, this structure has the advantage of being easy to implement. It also makes the animation model independent. Therefore, if you register an animation, you can use it in all models. (As long as the models have the same binding pose structure. Note that some Mixamo models have different binding poses.)

But I think it would be better to put them together.

So, in the future, I'm going to have an import manager and create a system that combines the two processes and manages resources.

**Comment by jinfagang** [comment]
@Nor-s thanks, after your explaination, i now though depart them from each other could be better.
SO that animations with BVH and model with FBX can be work out of box.

Will catch u up with this project! 

BTW, I found I can not using the camera (touchpad in mac) can not freely turn around the model, is it normal?

**Comment by jinfagang** [comment]
I tried edit animation class, but the result still not right:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/21303438/172397799-63c2a261-f7c6-4469-8ba7-318046838319.png">


and the texture seems not right as well.

models.cpp:

```
 unsigned int assimp_read_flag = aiProcess_Triangulate |
                                        aiProcess_SortByPType |
                                        aiProcess_GenUVCoords |
                                        aiProcess_OptimizeMeshes |
                                        aiProcess_ValidateDataStructure |
                                        // aiProcess_ConvertToLeftHanded |
                                        aiProcess_FlipUVs |
                                        aiProcess_GenNormals |
                                        aiProcess_CalcTangentSpace;
        assimp_read_flag |= aiProcess_LimitBoneWeights;
        assimp_read_flag |= aiProcess_JoinIdenticalVertices;
        assimp_read_flag |= aiProcess_FlipWindingOrder;
        import.SetPropertyBool(AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, false);
```

animation.cpp

```
  unsigned int assimp_read_flag =
                aiProcess_SortByPType |
                aiProcess_ValidateDataStructure |
                aiProcess_ConvertToLeftHanded |
                aiProcess_LimitBoneWeights;

            importer.SetPropertyBool(AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS, false);
```

why it was so not right?

**Comment by jinfagang** [comment]
<img width="422" alt="image" src="https://user-images.githubusercontent.com/21303438/172398282-8d6e1350-ec3e-4486-8f42-e794e0deadbb.png">

the mesh also cavity.

**Comment by jinfagang** [comment]
@Nor-s thanks, I will try `aiProcess_MakeLeftHanded` later.

why does the system platform will effect the animation loading way? it didn't make sense. Have u tried download some mixamo fbx model file and visualize?

**Comment by Nor-s** [comment]
i find model error but this model 

But This model gave an error even when I run it on Blender.
![screenshot (14)](https://user-images.githubusercontent.com/40836757/172531170-540719de-3875-4024-84d6-5721a7f7344b.gif)
![screenshot (17)](https://user-images.githubusercontent.com/40836757/172531185-aa5dde91-00e2-481f-b2c8-2e6f07aebf20.gif)

![screenshot (15)](https://user-images.githubusercontent.com/40836757/172531176-e75482ed-f4a9-4ad8-a616-075feb552e68.gif)

And if the model texture has an alpha value, the model may not be visible.

## Mixamo Load test

![화면 캡처 2022-06-08 130620](https://user-images.githubusercontent.com/40836757/172530825-a3744495-4d95-449c-9542-abb34385360c.png)
![화면 캡처 2022-06-08 130634](https://user-images.githubusercontent.com/40836757/172530834-717d3d7c-ff91-48ab-bb50-a0ea3e637570.png)
![화면 캡처 2022-06-08 130703](https://user-images.githubusercontent.com/40836757/172530842-e1f522b3-4d2d-46a8-bc6c-2f75cd2ab09e.png)
![화면 캡처 2022-06-08 130719](https://user-images.githubusercontent.com/40836757/172530862-6ab2c2f8-80cf-4822-a88e-4b01b79a439c.png)
![화면 캡처 2022-06-08 130733](https://user-images.githubusercontent.com/40836757/172530870-13c55579-54f6-4da4-a1e1-af4b23e46d26.png)
![화면 캡처 2022-06-08 131032](https://user-images.githubusercontent.com/40836757/172530877-f812d0e0-57da-45db-901c-929f7911da22.png)
![화면 캡처 2022-06-08 131053](https://user-images.githubusercontent.com/40836757/172530886-25464d0c-7952-4b73-b161-d8d7fd888456.png)

**Comment by jinfagang** [comment]
@Nor-s are u tested on macos? the only difference between you and me is system.

**Comment by Nor-s** [comment]
I really don't know why. It works fine on my macbook.

## mac os test
<img width="516" alt="image" src="https://user-images.githubusercontent.com/40836757/172738505-d73b65d8-c4c7-473c-a8eb-1d9870f813e9.png">

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/40836757/172738703-31a7d65b-479e-498b-8784-da9150d3b031.png">

![image](https://user-images.githubusercontent.com/40836757/172738397-929a5378-2297-4424-97bc-66437642b0d2.png)

![image](https://user-images.githubusercontent.com/40836757/172738406-149d9b2a-cd1c-46c1-ab45-dd2cbfd268d0.png)

![image](https://user-images.githubusercontent.com/40836757/172738414-d0e6643d-b68d-444c-894a-3ff8f6e28117.png)

![image](https://user-images.githubusercontent.com/40836757/172738423-950f50c4-752f-415f-96f1-21c55c827c5a.png)

![image](https://user-images.githubusercontent.com/40836757/172738429-afbb65e7-4dd6-4425-b2f9-9dfcccf20c0f.png)

![image](https://user-images.githubusercontent.com/40836757/172738443-c144b471-b569-4fca-85de-ce5863102db4.png)

**Comment by jinfagang** [comment]
@Nor-s  I am trying build pixe3d on a ubuntu, see if this platform is normal. I will clone a fresh repo to start.

**Comment by Nor-s** [comment]
Since I have never built in Ubuntu environment, I will also try it in wsl2 ubuntu environment.

**Comment by Nor-s** [comment]
##  platform
wsl2  Ubuntu 20.04.4 LTS (Focal Fossa)
gcc 9.4.0 x86_64-linux-gnu
## install

```
sudo apt install wget
sudo apt install openssl
sudo apt install ninja-build
sudo apt install build-essential
sudo apt-get install build-essential libgtk-3-dev
sudo apt-get install libxinerama-dev
sudo apt install libssl-dev
```
### CMAKE 3.23.2

```
wget https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2.tar.gz
tar -xvf cmake-3.23.2.tar.gz
cd cmake-3.23.2
./bootstrap --prefix=/usr
make
sudo make install
```
## Edit pixel3d/CMakeLists.txt

```
project(
  n-glcpp
  LANGUAGES CXX
  VERSION 0.0.5)
set(CMAKE_CXX_STANDARD 17)
if (UNIX AND NOT APPLE)
    set(CMAKE_MAKE_PROGRAM /usr/bin/ninja CACHE FILEPATH "")
endif()
```

## Build

```
git clone --recursive https://github.com/Nor-s/Pixel3D.git
cd Pixel3D
mkdir build
cd build
cmake .. -G Ninja
ninja
```

![image](https://user-images.githubusercontent.com/40836757/172819462-248ea6aa-2e32-4688-af7b-f6c42b20b1de.png)
